### ISSUE TITLE
Is there a way to make so this can use the local microphone that docker is running on?

### ISSUE THREAD

**Issue by NonaSuomy** [dalehumby/openWakeWord-rhasspy#2]
^

**Comment by arkharim** [comment]
@NonaSuomy are you asking to use in the same machine, both the base rhasspy installation plus a docker with openwake word? The answer is yes, it is possible. Just follow the procedure explained but un the udp_ports use default as siteId.

For example, my configuration is:

- OpenWakeWord:

``` yaml
   udp_ports:
      default: 12202  # Delete or change as needed
```  
- Docker compose:

  ``` yaml
    rhasspy:
    image: rhasspy/rhasspy
    container_name: rhasspy
    volumes:
        - $HOME/appdata/rhasspy/profiles:/profiles
        - /etc/localtime:/etc/localtime:ro
        - $HOME/ssl_certificates/:/profiles/cert
    ports:
        - 12101:12101
    devices:
        - /dev/snd:/dev/snd
    command: --user-profiles /profiles --profile es
    depends_on: 
      - mosquitto #The external MQTT server
      - openwakeword    
    restart: unless-stopped

    openwakeword:
    image: dalehumby/openwakeword-rhasspy
    container_name: openwakeword    
    ports:
      - 12202:12202/udp
    volumes:
      - $HOME/appdata/rhasspy/openwakeword:/config
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
```
